apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: opa-kube-scheduler
  name: opa-kube-scheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: opa-kube-scheduler
      name: opa-kube-scheduler
    spec:
      containers:
        - name: opa-kube-scheduler
          image: openpolicyagent/opa-kube-scheduler:0.1.2
          env:
          - name: KUBERNETES_SERVICE_HOST
            value: kubernetes
          - name: KUBERNETES_SERVICE_PORT
            value: "443"
