apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
      annotations:
        scheduler.alpha.kubernetes.io/name: experimental
    spec:
      containers:
      - name: nginx
        image: nginx
